package server

import (
	"errors"
	"net/netip"
	"strings"
	"testing"

	"warptweet.com/warptweet/internal/profile"
)

func TestRenderProducesExactForwardingOnlyConfiguration(t *testing.T) {
	t.Parallel()

	config := validConfig()
	got, err := Render(config)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	want := `# Generated by WarpTweet. Do not edit.
AddressFamily inet
Port 2222
ListenAddress 192.0.2.10
PidFile /run/warptweet/sshd/warptweet-sshd.pid
HostKey /var/lib/warptweet/ssh/ssh_host_mldsa44_ed25519_key
HostKeyAlgorithms ssh-mldsa44-ed25519@openssh.com
KexAlgorithms mlkem768x25519-sha256
PubkeyAcceptedAlgorithms ssh-mldsa44-ed25519@openssh.com
Ciphers chacha20-poly1305@openssh.com
RekeyLimit 512M 1h
Compression no
AuthenticationMethods publickey
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
StrictModes yes
AllowUsers warptweet
AuthorizedKeysFile /var/lib/warptweet/authorized_keys/warptweet
MaxAuthTries 3
LoginGraceTime 30
MaxStartups 10:30:60
MaxSessions 0
AllowTcpForwarding local
PermitOpen 198.51.100.7:5432 127.0.0.1:29723
PermitListen none
AllowStreamLocalForwarding no
AllowAgentForwarding no
X11Forwarding no
PermitTTY no
PermitTunnel no
GatewayPorts no
PermitUserRC no
PermitUserEnvironment no
ExposeAuthInfo no
PrintLastLog no
PrintMotd no
UseDNS no
TCPKeepAlive no
ClientAliveInterval 30
ClientAliveCountMax 3
VersionAddendum none
LogLevel VERBOSE
`
	if string(got) != want {
		t.Fatalf("unexpected sshd_config:\n--- got ---\n%s--- want ---\n%s", got, want)
	}

	again, err := Render(config)
	if err != nil {
		t.Fatalf("second Render: %v", err)
	}
	if string(again) != string(got) {
		t.Fatal("Render returned nondeterministic output")
	}

	for _, forbidden := range []string{
		"DisableForwarding",
		"Subsystem",
		"ForceCommand",
		"AllowTcpForwarding yes",
		"PasswordAuthentication yes",
		"UsePAM yes",
	} {
		if strings.Contains(string(got), forbidden) {
			t.Fatalf("rendered forbidden directive %q", forbidden)
		}
	}
}

func TestRenderFormatsIPv6WithoutBroadeningPermitOpen(t *testing.T) {
	t.Parallel()

	config := validConfig()
	config.Network = PublicationNetwork(netip.MustParseAddr("2001:db8::10"), 2222, 29722)
	config.Target = Endpoint{
		Address: netip.MustParseAddr("2001:db8::20"),
		Port:    443,
	}

	got, err := Render(config)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "AddressFamily inet6\n") {
		t.Fatalf("missing IPv6 address family:\n%s", text)
	}
	if !strings.Contains(text, "ListenAddress 2001:db8::10\n") {
		t.Fatalf("missing IPv6 listen address:\n%s", text)
	}
	if !strings.Contains(text, "PermitOpen [2001:db8::20]:443 127.0.0.1:29723\n") {
		t.Fatalf("PermitOpen did not render a single bracketed IPv6 target:\n%s", text)
	}
}

func TestRenderCanonicalizesIPv4MappedAddresses(t *testing.T) {
	t.Parallel()

	config := validConfig()
	config.Network.Data.Listen.Address = netip.MustParseAddr("::ffff:192.0.2.10")
	config.Network.Enrollment.Listen.Address = netip.MustParseAddr("::ffff:192.0.2.10")
	config.Network.Data.Dial.Host = IPDialHost(netip.MustParseAddr("::ffff:192.0.2.10"))
	config.Network.Enrollment.Dial.Host = IPDialHost(netip.MustParseAddr("::ffff:192.0.2.10"))
	config.Target.Address = netip.MustParseAddr("::ffff:198.51.100.7")

	got, err := Render(config)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	text := string(got)
	if !strings.Contains(text, "AddressFamily inet\n") ||
		!strings.Contains(text, "ListenAddress 192.0.2.10\n") ||
		!strings.Contains(text, "PermitOpen 198.51.100.7:5432 127.0.0.1:29723\n") {
		t.Fatalf("mapped addresses were not rendered canonically:\n%s", text)
	}
}

func TestRenderUsesDataListenNotPublishedDial(t *testing.T) {
	t.Parallel()

	config := validConfig()
	config.Network.Data.Dial = DialEndpoint{
		Host: IPDialHost(netip.MustParseAddr("34.20.174.226")),
		Port: 2222,
	}
	config.Network.Enrollment.Dial = DialEndpoint{
		Host: IPDialHost(netip.MustParseAddr("34.20.174.226")),
		Port: 29722,
	}

	got, err := Render(config)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	text := string(got)
	if strings.Contains(text, "34.20.174.226") {
		t.Fatalf("Render wrote a published dial into sshd_config:\n%s", text)
	}
	if !strings.Contains(text, "ListenAddress 192.0.2.10\n") || !strings.Contains(text, "Port 2222\n") {
		t.Fatalf("Render did not use data listen:\n%s", text)
	}
}

func TestValidateAllowsLoopbackBindAndDial(t *testing.T) {
	t.Parallel()

	config := validConfig()
	config.Network = PublicationNetwork(netip.MustParseAddr("127.0.0.1"), 2222, 29722)
	if err := Validate(config); err != nil {
		t.Fatalf("Validate rejected loopback bind and dial: %v", err)
	}
}

func TestValidateRejectsSchemaVersion1(t *testing.T) {
	t.Parallel()

	config := validConfig()
	config.SchemaVersion = 1
	err := Validate(config)
	if err == nil {
		t.Fatal("Validate accepted schema 1")
	}
	if !errors.Is(err, ErrInvalidConfig) || !strings.Contains(err.Error(), "SchemaVersion") {
		t.Fatalf("error = %v", err)
	}
}

func TestValidateRejectsUnsafeInputs(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		mutate func(*Config)
		field  string
	}{
		{
			name: "wrong manifest kind",
			mutate: func(config *Config) {
				config.Kind = "warptweet.client"
			},
			field: "Kind",
		},
		{
			name: "wrong schema version",
			mutate: func(config *Config) {
				config.SchemaVersion = 1
			},
			field: "SchemaVersion",
		},
		{
			name: "unknown profile",
			mutate: func(config *Config) {
				config.ProfileID = "pq-preferred"
			},
			field: "ProfileID",
		},
		{
			name: "missing sshd digest",
			mutate: func(config *Config) {
				config.SSHDBinarySHA256 = ""
			},
			field: "SSHDBinarySHA256",
		},
		{
			name: "short sshd digest",
			mutate: func(config *Config) {
				config.SSHDBinarySHA256 = strings.Repeat("a", 63)
			},
			field: "SSHDBinarySHA256",
		},
		{
			name: "uppercase sshd digest",
			mutate: func(config *Config) {
				config.SSHDBinarySHA256 = strings.Repeat("A", 64)
			},
			field: "SSHDBinarySHA256",
		},
		{
			name: "nonhexadecimal sshd digest",
			mutate: func(config *Config) {
				config.SSHDBinarySHA256 = strings.Repeat("g", 64)
			},
			field: "SSHDBinarySHA256",
		},
		{
			name: "missing bundle manifest digest",
			mutate: func(config *Config) {
				config.OpenSSHBundleManifestSHA256 = ""
			},
			field: "OpenSSHBundleManifestSHA256",
		},
		{
			name: "short bundle manifest digest",
			mutate: func(config *Config) {
				config.OpenSSHBundleManifestSHA256 = strings.Repeat("b", 63)
			},
			field: "OpenSSHBundleManifestSHA256",
		},
		{
			name: "uppercase bundle manifest digest",
			mutate: func(config *Config) {
				config.OpenSSHBundleManifestSHA256 = strings.Repeat("B", 64)
			},
			field: "OpenSSHBundleManifestSHA256",
		},
		{
			name: "nonhexadecimal bundle manifest digest",
			mutate: func(config *Config) {
				config.OpenSSHBundleManifestSHA256 = strings.Repeat("z", 64)
			},
			field: "OpenSSHBundleManifestSHA256",
		},
		{
			name: "invalid listen address",
			mutate: func(config *Config) {
				config.Network.Data.Listen.Address = netip.Addr{}
			},
			field: "Network.Data.Listen.Address",
		},
		{
			name: "wildcard IPv4 listen address",
			mutate: func(config *Config) {
				config.Network.Data.Listen.Address = netip.MustParseAddr("0.0.0.0")
			},
			field: "Network.Data.Listen.Address",
		},
		{
			name: "wildcard IPv6 listen address",
			mutate: func(config *Config) {
				config.Network.Data.Listen.Address = netip.MustParseAddr("::")
			},
			field: "Network.Data.Listen.Address",
		},
		{
			name: "multicast listen address",
			mutate: func(config *Config) {
				config.Network.Data.Listen.Address = netip.MustParseAddr("224.0.0.1")
			},
			field: "Network.Data.Listen.Address",
		},
		{
			name: "zoned listen address",
			mutate: func(config *Config) {
				config.Network.Data.Listen.Address = netip.MustParseAddr("fe80::1%eth0")
			},
			field: "Network.Data.Listen.Address",
		},
		{
			name: "zero listen port",
			mutate: func(config *Config) {
				config.Network.Data.Listen.Port = 0
			},
			field: "Network.Data.Listen.Port",
		},
		{
			name: "zero published_endpoint_generation",
			mutate: func(config *Config) {
				config.Network.PublishedEndpointGeneration = 0
			},
			field: "Network.PublishedEndpointGeneration",
		},
		{
			name: "unspecified dial IP",
			mutate: func(config *Config) {
				config.Network.Data.Dial.Host = IPDialHost(netip.MustParseAddr("0.0.0.0"))
			},
			field: "Network.Data.Dial.Host",
		},
		{
			name: "multicast dial IP",
			mutate: func(config *Config) {
				config.Network.Data.Dial.Host = IPDialHost(netip.MustParseAddr("224.0.0.1"))
			},
			field: "Network.Data.Dial.Host",
		},
		{
			name: "broadcast dial IP",
			mutate: func(config *Config) {
				config.Network.Data.Dial.Host = IPDialHost(netip.MustParseAddr("255.255.255.255"))
			},
			field: "Network.Data.Dial.Host",
		},
		{
			name: "link-local dial IP",
			mutate: func(config *Config) {
				config.Network.Data.Dial.Host = IPDialHost(netip.MustParseAddr("169.254.1.1"))
			},
			field: "Network.Data.Dial.Host",
		},
		{
			name: "loopback dial with non-loopback bind",
			mutate: func(config *Config) {
				config.Network.Data.Dial.Host = IPDialHost(netip.MustParseAddr("127.0.0.1"))
			},
			field: "Network.Data.Dial.Host",
		},
		{
			name: "non-loopback dial with loopback bind",
			mutate: func(config *Config) {
				config.Network = PublicationNetwork(netip.MustParseAddr("127.0.0.1"), 2222, 29722)
				config.Network.Data.Dial.Host = IPDialHost(netip.MustParseAddr("192.0.2.10"))
			},
			field: "Network.Data.Dial.Host",
		},
		{
			name: "bind address port collision",
			mutate: func(config *Config) {
				config.Network.Enrollment.Listen.Port = 2222
			},
			field: "Network",
		},
		{
			name: "dial host port collision including IPv4-mapped",
			mutate: func(config *Config) {
				config.Network.Enrollment.Dial = DialEndpoint{
					Host: IPDialHost(netip.MustParseAddr("::ffff:192.0.2.10")),
					Port: 2222,
				}
			},
			field: "Network",
		},
		{
			name: "invalid target address",
			mutate: func(config *Config) {
				config.Target.Address = netip.Addr{}
			},
			field: "Target.Address",
		},
		{
			name: "wildcard target address",
			mutate: func(config *Config) {
				config.Target.Address = netip.MustParseAddr("::ffff:0.0.0.0")
			},
			field: "Target.Address",
		},
		{
			name: "multicast target address",
			mutate: func(config *Config) {
				config.Target.Address = netip.MustParseAddr("ff02::1")
			},
			field: "Target.Address",
		},
		{
			name: "broadcast target address",
			mutate: func(config *Config) {
				config.Target.Address = netip.MustParseAddr("255.255.255.255")
			},
			field: "Target.Address",
		},
		{
			name: "zero target port",
			mutate: func(config *Config) {
				config.Target.Port = 0
			},
			field: "Target.Port",
		},
		{
			name: "empty user",
			mutate: func(config *Config) {
				config.DedicatedUser = ""
			},
			field: "DedicatedUser",
		},
		{
			name: "root user",
			mutate: func(config *Config) {
				config.DedicatedUser = "root"
			},
			field: "DedicatedUser",
		},
		{
			name: "reserved sshd user",
			mutate: func(config *Config) {
				config.DedicatedUser = "sshd"
			},
			field: "DedicatedUser",
		},
		{
			name: "option-shaped user",
			mutate: func(config *Config) {
				config.DedicatedUser = "-oPermitRootLogin"
			},
			field: "DedicatedUser",
		},
		{
			name: "uppercase user",
			mutate: func(config *Config) {
				config.DedicatedUser = "WarpTweet"
			},
			field: "DedicatedUser",
		},
		{
			name: "long user",
			mutate: func(config *Config) {
				config.DedicatedUser = strings.Repeat("a", 33)
			},
			field: "DedicatedUser",
		},
		{
			name: "relative host key",
			mutate: func(config *Config) {
				config.HostKeyPath = "etc/host-key"
			},
			field: "HostKeyPath",
		},
		{
			name: "noncanonical host key",
			mutate: func(config *Config) {
				config.HostKeyPath = "/opt/warptweet/../host-key"
			},
			field: "HostKeyPath",
		},
		{
			name: "alternate absolute host key",
			mutate: func(config *Config) {
				config.HostKeyPath = "/opt/warptweet/etc/alternate-host-key"
			},
			field: "HostKeyPath",
		},
		{
			name: "host key with directive injection",
			mutate: func(config *Config) {
				config.HostKeyPath = "/opt/warptweet/host-key\nPermitRootLogin yes"
			},
			field: "HostKeyPath",
		},
		{
			name: "relative authorized keys",
			mutate: func(config *Config) {
				config.AuthorizedKeysPath = "authorized_keys"
			},
			field: "AuthorizedKeysPath",
		},
		{
			name: "tokenized authorized keys",
			mutate: func(config *Config) {
				config.AuthorizedKeysPath = "/opt/warptweet/authorized_keys/%u"
			},
			field: "AuthorizedKeysPath",
		},
		{
			name: "filesystem root authorized keys",
			mutate: func(config *Config) {
				config.AuthorizedKeysPath = "/"
			},
			field: "AuthorizedKeysPath",
		},
		{
			name: "alternate absolute authorized keys",
			mutate: func(config *Config) {
				config.AuthorizedKeysPath = "/opt/warptweet/etc/authorized_keys/alternate"
			},
			field: "AuthorizedKeysPath",
		},
		{
			name: "authorized keys does not follow dedicated user",
			mutate: func(config *Config) {
				config.DedicatedUser = "database"
			},
			field: "AuthorizedKeysPath",
		},
		{
			name: "shared private and authorized key path",
			mutate: func(config *Config) {
				config.AuthorizedKeysPath = config.HostKeyPath
			},
			field: "AuthorizedKeysPath",
		},
	}

	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			config := validConfig()
			test.mutate(&config)
			err := Validate(config)
			if err == nil {
				t.Fatal("Validate accepted unsafe input")
			}
			if !errors.Is(err, ErrInvalidConfig) {
				t.Fatalf("error does not wrap ErrInvalidConfig: %v", err)
			}
			if !strings.Contains(err.Error(), test.field) {
				t.Fatalf("error %q does not identify field %q", err, test.field)
			}
		})
	}
}

func validConfig() Config {
	return Config{
		Kind:                        ManifestKind,
		SchemaVersion:               CurrentSchemaVersion,
		ProfileID:                   profile.CurrentID,
		SSHDBinarySHA256:            strings.Repeat("a", 64),
		OpenSSHBundleManifestSHA256: strings.Repeat("b", 64),
		Network:                     PublicationNetwork(netip.MustParseAddr("192.0.2.10"), 2222, 29722),
		Target: Endpoint{
			Address: netip.MustParseAddr("198.51.100.7"),
			Port:    5432,
		},
		DedicatedUser:      DefaultDedicatedUser,
		HostKeyPath:        "/var/lib/warptweet/ssh/ssh_host_mldsa44_ed25519_key",
		AuthorizedKeysPath: "/var/lib/warptweet/authorized_keys/warptweet",
	}
}
