// Package server renders the restricted OpenSSH server configuration used by
// WarpTweet tunnel gateways.
package server

import (
	"errors"
	"fmt"
	"net/netip"
	"strings"

	"warptweet.com/warptweet/internal/installlayout"
	"warptweet.com/warptweet/internal/profile"
)

const (
	// DefaultDedicatedUser is the locked operating-system account that package
	// installations should provision for authenticated tunnel connections.
	DefaultDedicatedUser = "warptweet"

	runtimePIDFile = "/run/warptweet/server/warptweet-sshd.pid"
	maxUserLength  = 32
	sha256HexBytes = 64
)

// ErrInvalidConfig identifies a server configuration that is unsafe to render.
var ErrInvalidConfig = errors.New("invalid WarpTweet server configuration")

// Port is a TCP port. Its signed representation lets validation reject both
// negative values and values above the protocol limit at input boundaries.
type Port int

// Endpoint is a numeric TCP endpoint. Address must be a concrete, unzoned
// unicast address. Hostnames are deliberately not representable.
type Endpoint struct {
	Address netip.Addr `json:"address"`
	Port    Port       `json:"port"`
}

// Config contains the server policy, fixed-layout asset references, and pinned
// engine digests. Paths are not opened by Render, so provisioning remains a
// separate step.
type Config struct {
	Kind                        string   `json:"kind"`
	SchemaVersion               int      `json:"schema_version"`
	ProfileID                   string   `json:"profile_id"`
	SSHDBinarySHA256            string   `json:"sshd_binary_sha256"`
	OpenSSHBundleManifestSHA256 string   `json:"openssh_bundle_manifest_sha256"`
	Listen                      Endpoint `json:"listen"`
	Target                      Endpoint `json:"target"`
	DedicatedUser               string   `json:"dedicated_user"`
	HostKeyPath                 string   `json:"host_key_path"`
	AuthorizedKeysPath          string   `json:"authorized_keys_path"`
}

// Validate rejects any configuration that could broaden the managed tunnel's
// authentication, forwarding, address, or filesystem policy.
func Validate(config Config) error {
	_, err := validate(config)
	return err
}

// Render returns a deterministic, forwarding-only sshd_config. Algorithm lists
// replace OpenSSH defaults; they are never appended to them.
func Render(config Config) ([]byte, error) {
	selectedProfile, err := validate(config)
	if err != nil {
		return nil, err
	}

	listenAddress := canonicalAddress(config.Listen.Address)
	target := netip.AddrPortFrom(
		canonicalAddress(config.Target.Address),
		uint16(config.Target.Port),
	).String()
	addressFamily := "inet6"
	if listenAddress.Is4() {
		addressFamily = "inet"
	}

	lines := []string{
		"# Generated by WarpTweet. Do not edit.",
		"AddressFamily " + addressFamily,
		fmt.Sprintf("Port %d", config.Listen.Port),
		"ListenAddress " + listenAddress.String(),
		"PidFile " + runtimePIDFile,
		"HostKey " + config.HostKeyPath,
		"HostKeyAlgorithms " + selectedProfile.AuthenticationKeyType,
		"KexAlgorithms " + selectedProfile.KeyExchangeAlgorithm,
		"PubkeyAcceptedAlgorithms " + selectedProfile.AuthenticationKeyType,
		"Ciphers " + strings.Join(selectedProfile.Ciphers, ","),
		"RekeyLimit 512M 1h",
		"Compression no",
		"AuthenticationMethods publickey",
		"PubkeyAuthentication yes",
		"PasswordAuthentication no",
		"KbdInteractiveAuthentication no",
		"HostbasedAuthentication no",
		"PermitEmptyPasswords no",
		"PermitRootLogin no",
		"StrictModes yes",
		"AllowUsers " + config.DedicatedUser,
		"AuthorizedKeysFile " + config.AuthorizedKeysPath,
		"MaxAuthTries 3",
		"LoginGraceTime 30",
		"MaxStartups 10:30:60",
		"MaxSessions 0",
		"AllowTcpForwarding local",
		"PermitOpen " + target,
		"PermitListen none",
		"AllowStreamLocalForwarding no",
		"AllowAgentForwarding no",
		"X11Forwarding no",
		"PermitTTY no",
		"PermitTunnel no",
		"GatewayPorts no",
		"PermitUserRC no",
		"PermitUserEnvironment no",
		"ExposeAuthInfo no",
		"PrintLastLog no",
		"PrintMotd no",
		"UseDNS no",
		"TCPKeepAlive no",
		"ClientAliveInterval 30",
		"ClientAliveCountMax 3",
		"VersionAddendum none",
		"LogLevel VERBOSE",
	}

	return []byte(strings.Join(lines, "\n") + "\n"), nil
}

func validate(config Config) (profile.Profile, error) {
	if config.Kind != ManifestKind {
		return profile.Profile{}, invalidField(
			"Kind",
			"must be %q",
			ManifestKind,
		)
	}
	if config.SchemaVersion != CurrentSchemaVersion {
		return profile.Profile{}, invalidField(
			"SchemaVersion",
			"must be %d",
			CurrentSchemaVersion,
		)
	}

	selectedProfile, err := profile.Lookup(config.ProfileID)
	if err != nil {
		return profile.Profile{}, invalidField("ProfileID", "%v", err)
	}
	if len(selectedProfile.Ciphers) == 0 {
		return profile.Profile{}, invalidField("ProfileID", "profile %q has no ciphers", config.ProfileID)
	}
	if err := validateSHA256("SSHDBinarySHA256", config.SSHDBinarySHA256); err != nil {
		return profile.Profile{}, err
	}
	if err := validateSHA256(
		"OpenSSHBundleManifestSHA256",
		config.OpenSSHBundleManifestSHA256,
	); err != nil {
		return profile.Profile{}, err
	}

	if err := validateEndpoint("Listen", config.Listen); err != nil {
		return profile.Profile{}, err
	}
	if err := validateEndpoint("Target", config.Target); err != nil {
		return profile.Profile{}, err
	}
	if err := validateDedicatedUser(config.DedicatedUser); err != nil {
		return profile.Profile{}, err
	}
	if config.HostKeyPath != installlayout.ServerHostKeyPath {
		return profile.Profile{}, invalidField(
			"HostKeyPath",
			"must be fixed package path %q",
			installlayout.ServerHostKeyPath,
		)
	}
	expectedAuthorizedKeysPath := managedAuthorizedKeysPath(config.DedicatedUser)
	if config.AuthorizedKeysPath != expectedAuthorizedKeysPath {
		return profile.Profile{}, invalidField(
			"AuthorizedKeysPath",
			"must be fixed package path %q for dedicated user %q",
			expectedAuthorizedKeysPath,
			config.DedicatedUser,
		)
	}

	return selectedProfile, nil
}

func validateEndpoint(field string, endpoint Endpoint) error {
	if !endpoint.Address.IsValid() {
		return invalidField(field+".Address", "must be a numeric IP address")
	}
	if endpoint.Address.Zone() != "" {
		return invalidField(field+".Address", "IPv6 zones are not permitted")
	}

	address := canonicalAddress(endpoint.Address)
	if address.IsUnspecified() {
		return invalidField(field+".Address", "wildcard addresses are not permitted")
	}
	if address.IsMulticast() {
		return invalidField(field+".Address", "multicast addresses are not permitted")
	}
	if address.Is4() && address == netip.AddrFrom4([4]byte{255, 255, 255, 255}) {
		return invalidField(field+".Address", "the IPv4 broadcast address is not permitted")
	}
	if endpoint.Port < 1 || endpoint.Port > 65535 {
		return invalidField(field+".Port", "must be between 1 and 65535")
	}

	return nil
}

func validateDedicatedUser(user string) error {
	if user == "" {
		return invalidField("DedicatedUser", "must not be empty")
	}
	if len(user) > maxUserLength {
		return invalidField("DedicatedUser", "must be at most %d ASCII characters", maxUserLength)
	}
	if !isUserInitial(user[0]) {
		return invalidField(
			"DedicatedUser",
			"must start with a lowercase ASCII letter or underscore",
		)
	}
	for index := 1; index < len(user); index++ {
		if !isUserContinuation(user[index]) {
			return invalidField(
				"DedicatedUser",
				"contains an unsafe character at byte %d",
				index,
			)
		}
	}

	switch user {
	case "root", "daemon", "nobody", "sshd", "_sshd":
		return invalidField("DedicatedUser", "%q is not a dedicated tunnel account", user)
	}

	return nil
}

func validateSHA256(field, value string) error {
	if len(value) != sha256HexBytes {
		return invalidField(field, "must contain exactly 64 lowercase hexadecimal characters")
	}
	for _, character := range []byte(value) {
		if character >= '0' && character <= '9' || character >= 'a' && character <= 'f' {
			continue
		}
		return invalidField(field, "must contain exactly 64 lowercase hexadecimal characters")
	}
	return nil
}

func canonicalAddress(address netip.Addr) netip.Addr {
	return address.Unmap()
}

func isUserInitial(value byte) bool {
	return value == '_' || value >= 'a' && value <= 'z'
}

func isUserContinuation(value byte) bool {
	return isUserInitial(value) || value >= '0' && value <= '9' || value == '-'
}

func managedAuthorizedKeysPath(user string) string {
	return installlayout.AuthorizedKeysDirectory + "/" + user
}

func invalidField(field, format string, args ...any) error {
	return fmt.Errorf("%w: %s: %s", ErrInvalidConfig, field, fmt.Sprintf(format, args...))
}
